### ISSUE TITLE
Request did not arrive, or the server blocked the request.

### ISSUE THREAD

**Issue by RaXorX** [Fornaxian/pixeldrain_web#10]
![image](https://github.com/Fornaxian/pixeldrain_web/assets/44987810/1cd9d9ad-e40d-4bab-bfc2-bc9fe87359ca)

I started using PixelDrain couple months back. Initial experience was well and good except for the fact that from next time onward, PixelDrain on my desktop has started to give me issues. I can't upload files anymore, at all. Tried other browsers, tried clearing DNS cache, tried using the cmd line tools as well. But no dice.

Even the cmd tools fail to upload for some reason. I'm not sure what's causing this error. While on the same network on my phone I can upload just fine from the app or the browser as well. It's just from my desktop where I can't.

**Comment by Fornax96** [comment]
This usually means there is some kind of program between the browser and my server which is intercepting the request. Try disabling your antivirus temporarily to see if that helps.
