### ISSUE TITLE
Question About Project 

### ISSUE THREAD

**Issue by LYZENCORE-9** [Fornaxian/pixeldrain_web#13]
**can i contribute on project or repository or this is restricted for no members in organization ?**

**Comment by Fornax96** [comment]
Hi, sorry for leaving you hanging like that.

I'm currently not looking for contributors. I prefer working on this project alone. But if you would like to change something you're free to submit a PR. I will review the changes and accept them if they're good. Please let me know beforehand what you would like to change.
