### ISSUE TITLE
Uploading file hangs at 100%

### ISSUE THREAD

**Issue by refriedfood** [Fornaxian/pixeldrain_web#17]
Using either the filesystem or myfiles feature, when using either firefox or chrome, the uploaded file tends to hang at 100%. It sits there after it has been uploaded, sometimes over an hour, before either staling completely and having to be reuploaded (often with the same results) or simply failing all together at 100%.

Please look into this.

**Comment by refriedfood** [comment]
I just wanted to note here, because it didn't seem worthy of opening another topic, but it seems your system favors chrome over firefox. When I upload/download from firefox I max out at about 1Mb/s up, 10Mb/s down, but with chrome its about 4 times that amount. The issue of it freezing at the end of the upload is gone for both, however.

**Comment by Fornax96** [comment]
@refriedfood I develop the site in Firefox too and I have not noticed any difference. It's possible that chrome opens the connection with different socket options resulting in better performance, but there's nothing I can do about that.

**Comment by refriedfood** [comment]
No problem. As long as you're aware.

**Comment by refriedfood** [comment]
I didn't want to open another ticket, but it seems as though the upload rate via firefox is limited or capped at 1.2-1.5MB/s whereas chrome uses the full speed of your line. Does this have to do with the browsers protocols?

I've tried on two separate versions of firefox and they both do it.

**Comment by Fornax96** [comment]
Could also have something to do with the server it picks. Pixeldrain has multiple servers in each location. Some are faster than others. I'm working on getting equally fast servers everywhere.
